fix: multiple rare ringing issues in react-native (#1611)
1. When permission was denied in RN. It was not properly handled. 

Now after this change, if permissions are not granted in RN, our client
properly logs like below

```
ERROR: [devices]: Failed to get audio stream {"constraints": {"audio": {"autoGainControl": true, "deviceId": undefined, "echoCancellation": true, "noiseSuppression": true}}, "error": {"constraintName": undefined, "message": "Permission denied.", "name": "SecurityError"}}
 ERROR: [permissions]: Failed to getUserMedia {"error": {"constraintName": undefined, "message": "Permission denied.", "name": "SecurityError"}, "permission": {"constraints": {"video": [Object]}, "queryName": "camera"}}
```

2. `DOMException ` is not present in RN, so must check for it 

3. Foreground notification can rarely make app go to PiP automatically,
fixed in this

4. hot reloads could add multiple listeners, causing push to be
processed twice.. fixed here

5. App going to background, could disable unnecessarily, fixed here

6. Removed the camera handling in incmoing call component to fix race on
foreground notification

7. updated the firebase setup with both samples inside stream-video
project

8. Apply importance: 4 to ringing notifications, support request..
channel was already set to this, so doesnt change anything actually

---------

Co-authored-by: Oliver Lazoroski <oliver.lazoroski@gmail.com>