chore(rn-video): upgrade to expo ver 52 (#1630)
## Overview
Upgrades the expo version in the expo-video-sample app to 52

- Fixes android issues: duplicated image resources with *.webp extension
```
> Task :app:mergeDebugResources FAILED
ERROR: [mipmap-mdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-mdpi/ic_launcher.webp [mipmap-mdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-mdpi/ic_launcher.png: Resource and asset merger: Duplicate resources
ERROR: [mipmap-mdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png [mipmap-mdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp: Resource and asset merger: Duplicate resources
ERROR: [mipmap-hdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-hdpi/ic_launcher.webp [mipmap-hdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-hdpi/ic_launcher.png: Resource and asset merger: Duplicate resources
ERROR: [mipmap-hdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png [mipmap-hdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xxxhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp [mipmap-xxxhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xxxhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png [mipmap-xxxhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xxhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp [mipmap-xxhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xxhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png [mipmap-xxhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp [mipmap-xhdpi-v4/ic_launcher] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png: Resource and asset merger: Duplicate resources
ERROR: [mipmap-xhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png [mipmap-xhdpi-v4/ic_launcher_round] /Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp: Resource and asset merger: Duplicate resources
```
 
- Fixes Type incompatibility issues:
```
error TS2345: Argument of type 'import("/Users/mkristian/Projects/stream/stream-video-js/sample-apps/react-native/expo-video-sample/node_modules/expo-notifications/build/Notifications.types").Notification' is not assignable to parameter of type 'import("/Users/mkristian/Projects/stream/stream-video-js/packages/react-native-sdk/node_modules/expo-notifications/build/Notifications.types").Notification'.
  The types of 'request.trigger' are incompatible between these types.
```
```
TS2339: Property 'type' does not exist on type 'number | PushNotificationTrigger | LocationNotificationTrigger | ChannelAwareTriggerInput | ... 8 more ... | UnknownNotificationTrigger'.
[@stream-io/video-react-native-sdk]:   Property 'type' does not exist on type 'number'.
[@stream-io/video-react-native-sdk]:
[@stream-io/video-react-native-sdk]: 38     if (event.request.trigger?.type === 'push') {
```
To solve these issues we needed to:
- bump the `react-native-sdk` expo-notification version to
`"expo-notifications": "~0.29.11"` to be in sync with the one used in
the `expo-video-sample` app.
- create new `isPushNotification` util method to do the type checks

---------

Co-authored-by: Santhosh Vaiyapuri <santhoshvai@gmail.com>