fix(codecs): Set codec preferences based on receiving capabilities (#1318)
Chrome 124 introduces a breaking change in how codec preferences are
handled. This led to some compatibility issues in our SDK:
```
DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': 
Invalid codec preferences: invalid codec with name "AV1".

DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver':
Invalid codec preferences: invalid codec with name "H264".
```

This PR adjusts the codec selection according to the recommendations
listed here:
- https://issues.chromium.org/issues/328396178
- https://groups.google.com/g/discuss-webrtc/c/QS7y-7zR5ok