fix: use `@types/ws` as a regular dependency (#1115)
`@types/ws` is referenced from the emitted types, making it a regular
package that should be installed by default.
Fixes:
```
$ node_modules/.bin/tsc
node_modules/@stream-io/video-client/dist/src/coordinator/connection/connection.d.ts:2:23 - error TS2688: Cannot find type definition file for 'ws'.

2 /// <reference types="ws" />
                        ~~
```

Prior to this, projects using `ts-node` or something similar for
server-side integration, failed to compile without applying workarounds
as:
- set `skipLibCheck: true` in `tsconfig.json` or
- adding `@types/ws` as a dev dependency to their project

As part of this PR, some dependencies got updated to their latest
versions.