fix: promise rejection on call leave (#767)
without this,

when pc.close is done, negotiate is called immediately on RN and maybe
also non chromium browsers?! and results in the following error

```
Possible Unhandled Promise Rejection (id: 1):
Error: CreateOffer called when PeerConnection is closed.
```